# soundbind.yaml
keybinds:
  - key: "1"
    sound: "../../assets/sounds/danca-gatinho.mp3"
    description: "Danca gatinho sound"
    stopOthers: true

  - key: "2"
    sound: "../../assets/sounds/oloquinho.mp3"
    description: "Oloquinho sound"

  - key: "3"
    sound: "../../assets/sounds/omaewa.mp3"
    description: "Omaewa sound"

audio:
  player: "play"

# Logging configuration
logging:
  level: "debug" # debug, info, warn, error
  fileEnabled: true
  filePath: "logs"
