# soundbind.yaml
keybinds:
  - key: "1"
    sound: "../../assets/sounds/danca-gatinho.mp3"
    description: "Danca gatinho sound"
    stopOthers: true

  - key: "2"
    sound: "../../assets/sounds/oloquinho.mp3"
    description: "Oloquinho sound"

  - key: "3"
    sound: "../../assets/sounds/omaewa.mp3"
    description: "Omaewa sound"

  - key: "4"
    sound: "../../assets/sounds/awesome-music.mp3"
    description: "Awesome music sound"

  - key: "5"
    sound: "../../assets/sounds/sci-fi-picking-detector.mp3"
    description: "Sound of picking science detector"

  - key: "6"
    sound: "../../assets/sounds/neighing-horse.mp3"
    description: "Clean and dry recording of a neighing horse close mic'ed."

audio:
  player: "play"

# Logging configuration
logging:
  level: "debug" # debug, info, warn, error
  fileEnabled: true
  filePath: "logs"
