profile:
  name: "elonmusk-secretaria"
  description: "A meme(fun) music from Brazil"
  version: "1.0.0"

audio:
  player: "play"
  maxConcurrent: 5

keybinds:
  - key: "F1"
    sound: "../../assets/sounds/elonmusk-secretaria.mp3"
